;;; chezmoi-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from chezmoi.el

(register-definition-prefixes "chezmoi" '("chezmoi-"))


;;; Generated autoloads from chezmoi-core.el

(register-definition-prefixes "chezmoi-core" '("chezmoi-"))


;;; Generated autoloads from chezmoi-template.el

(register-definition-prefixes "chezmoi-template" '("chezmoi-template-"))

;;; End of scraped data

(provide 'chezmoi-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; chezmoi-autoloads.el ends here
